# Generated by Django 4.2.30 on 2026-07-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('applicant', 'Applicant'), ('committee_chairman', 'Local Government Chairman'), ('finance', 'Council Treasurer'), ('naming_committee', 'Street Naming Committee')], default='applicant', max_length=30),
        ),
    ]
