# Generated by Django 6.0.4 on 2026-04-16 22:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StreetType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'street_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeeConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('component', models.CharField(choices=[('application_fee', 'Application Fee'), ('inspection_fee', 'Inspection Fee'), ('radio_tv_tax', 'Radio/TV Tax'), ('committee_verification_fee', 'Committee Verification Fee'), ('street_name_fee', 'Street Name Fee'), ('signpost_installation_fee', 'Signpost Installation Fee'), ('map_upload_fee', 'Map Upload Fee'), ('renewal_fee', 'Renewal Fee')], max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_configs_updated', to=settings.AUTH_USER_MODEL)),
                ('street_type', models.ForeignKey(blank=True, help_text='Only for street_name_fee — varies per street type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.streettype')),
            ],
            options={
                'db_table': 'fee_configurations',
                'unique_together': {('component', 'street_type')},
            },
        ),
    ]
