# Generated by Django 6.0.4 on 2026-04-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeconfiguration',
            name='component',
            field=models.CharField(choices=[('application_fee', 'Application Fee'), ('inspection_fee', 'Inspection Fee'), ('radio_tv_tax', 'Radio/TV Tax'), ('committee_verification_fee', 'Committee Verification Fee'), ('street_name_fee', 'Street Name Fee'), ('signpost_installation_fee', 'Signpost Installation Fee'), ('map_upload_fee', 'Map Upload Fee'), ('renewal_fee', 'Renewal Fee')], max_length=50),
        ),
    ]
