# Generated by Django 6.0.4 on 2026-04-18 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_alter_buildingsurvey_enumerator_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RenewalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewal_years', models.PositiveSmallIntegerField(default=5, help_text='Number of years added to the current expiry date when a renewal is confirmed.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'renewal_settings',
            },
        ),
    ]
