# Generated by Django 4.2.30 on 2026-07-13 11:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_add_renewal_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('normalized_key', models.CharField(db_index=True, max_length=200, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('ward', models.CharField(blank=True, max_length=100)),
                ('locality', models.CharField(blank=True, max_length=200)),
                ('building_count', models.PositiveIntegerField(default=0)),
                ('name_variants', models.PositiveIntegerField(default=1, help_text='How many raw spellings merged into this street')),
                ('registration_status', models.CharField(choices=[('surveyed', 'Surveyed (named, not yet registered)'), ('registered', 'Registered')], default='surveyed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('street_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='streets', to='config.streettype')),
            ],
            options={
                'db_table': 'streets',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='buildingsurvey',
            name='street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buildings', to='config.street'),
        ),
    ]
