# Generated by Django 4.2.30 on 2026-07-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_street_latitude_street_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='street',
            name='geometry',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='street',
            name='source',
            field=models.CharField(choices=[('survey', 'Auto (from survey points)'), ('digitised', 'Digitised (ground-truth)')], default='survey', max_length=20),
        ),
    ]
