# Generated by Django 4.2.30 on 2026-08-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0009_street_geometry_street_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='street',
            name='validation_status',
            field=models.CharField(choices=[('google', 'Validation urgently required'), ('survey', 'Needs regularization'), ('registry', 'Collected from old registry')], db_index=True, default='survey', max_length=20),
        ),
    ]
