# Generated by Django 4.2.30 on 2026-08-16 13:59

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('config', '0010_street_validation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeconfiguration',
            name='component',
            field=models.CharField(choices=[('application_fee', 'Application Fee'), ('inspection_fee', 'Inspection Fee'), ('radio_tv_tax', 'Radio/TV Tax'), ('committee_verification_fee', 'Committee Verification Fee'), ('street_name_fee', 'Street Name Fee'), ('signpost_installation_fee', 'Signpost Installation Fee'), ('map_upload_fee', 'Map Upload Fee'), ('revalidation_fee', 'Revalidation Fee'), ('renewal_fee', 'Renewal Fee')], max_length=50),
        ),
        migrations.AlterField(
            model_name='feeconfiguration',
            name='street_type',
            field=models.ForeignKey(blank=True, help_text='For street_name_fee, revalidation_fee and renewal_fee — these vary per street type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.streettype'),
        ),
        migrations.CreateModel(
            name='FeePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revalidation_percent', models.DecimalField(decimal_places=2, default=Decimal('40.00'), help_text='Revalidation fee as a percentage of the street-name fee.', max_digits=5)),
                ('renewal_percent', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Renewal fee as a percentage of the street-name fee.', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_policy_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Fee policy',
                'db_table': 'fee_policy',
            },
        ),
    ]
