# Generated by Django 4.2.30 on 2026-08-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0011_alter_feeconfiguration_component_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=200)),
                ('highway', models.CharField(blank=True, help_text='OSM class: residential, trunk, track…', max_length=40)),
                ('geometry', models.TextField(help_text='GeoJSON LineString')),
                ('min_lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('max_lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('min_lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('max_lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'road_segments',
                'indexes': [models.Index(fields=['min_lat', 'max_lat'], name='road_segmen_min_lat_29dc6c_idx'), models.Index(fields=['min_lng', 'max_lng'], name='road_segmen_min_lng_f85186_idx')],
            },
        ),
    ]
