# Generated by Django 4.2.30 on 2026-07-21 10:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_application_latitude_application_locality_and_more'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('application_due', 'Application payment/action due'), ('expiry_3_months', '3 months before expiry'), ('expiry_1_month', '1 month before expiry'), ('expiry_due', 'On expiry date'), ('grace_start', 'Grace period started (day after expiry)'), ('grace_reminder', 'Grace period reminder (days left)')], max_length=32)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='applications.application')),
            ],
            options={
                'db_table': 'reminder_logs',
                'ordering': ['-sent_at'],
                'unique_together': {('application', 'stage')},
            },
        ),
    ]
