# Generated by Django 6.0.4 on 2026-04-16 22:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('proposed_street_name', models.CharField(max_length=200)),
                ('location_description', models.TextField()),
                ('lga_area', models.CharField(default='Ibeju-Lekki', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('awaiting_stage_a_payment', 'Awaiting Stage A Payment'), ('stage_a_confirmed', 'Stage A Confirmed'), ('under_naming_committee_review', 'Under Naming Committee Review'), ('approved_by_committee', 'Approved by Committee'), ('rejected_by_committee', 'Rejected by Committee'), ('awaiting_chairman_approval', 'Awaiting Chairman Approval'), ('approved_by_chairman', 'Approved by Chairman'), ('rejected_by_chairman', 'Rejected by Chairman'), ('awaiting_stage_c_payment', 'Awaiting Stage C Payment'), ('stage_c_confirmed', 'Stage C Confirmed'), ('certificate_issued', 'Certificate Issued'), ('expired', 'Expired'), ('renewal_submitted', 'Renewal Submitted'), ('awaiting_renewal_payment', 'Awaiting Renewal Payment'), ('renewal_payment_confirmed', 'Renewal Payment Confirmed'), ('renewed', 'Renewed'), ('withdrawn', 'Withdrawn')], default='draft', max_length=50)),
                ('committee_remarks', models.TextField(blank=True)),
                ('chairman_remarks', models.TextField(blank=True)),
                ('certificate_number', models.CharField(blank=True, max_length=50)),
                ('certificate_issued_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('street_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='config.streettype')),
            ],
            options={
                'db_table': 'applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(max_length=50)),
                ('to_status', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='applications.application')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'status_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
