# Generated by Django 6.0.4 on 2026-04-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ward',
            field=models.CharField(choices=[('ward_a', 'Ward A - Central'), ('ward_b', 'Ward B - North'), ('ward_c', 'Ward C - South')], default='ward_a', max_length=20),
        ),
    ]
