# Generated by Django 6.0.4 on 2026-04-18 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='application',
            name='google_map_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='signpost_installed',
            field=models.BooleanField(default=False),
        ),
    ]
