# Generated by Django 6.0.4 on 2026-04-18 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_add_certificate_file_and_completion_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('awaiting_stage_a_payment', 'Awaiting Stage A Payment'), ('awaiting_stage_a_payment_confirmation', 'Awaiting Stage A Payment Confirmation'), ('stage_a_confirmed', 'Stage A Confirmed'), ('under_naming_committee_review', 'Under Naming Committee Review'), ('approved_by_committee', 'Approved by Committee'), ('rejected_by_committee', 'Rejected by Committee'), ('awaiting_chairman_approval', 'Awaiting Chairman Approval'), ('approved_by_chairman', 'Approved by Chairman'), ('rejected_by_chairman', 'Rejected by Chairman'), ('awaiting_stage_c_payment', 'Awaiting Stage C Payment'), ('awaiting_stage_c_payment_confirmation', 'Awaiting Stage C Payment Confirmation'), ('stage_c_confirmed', 'Stage C Confirmed'), ('certificate_issued', 'Certificate Issued'), ('expired', 'Expired'), ('renewal_submitted', 'Renewal Submitted'), ('awaiting_renewal_payment', 'Awaiting Renewal Payment'), ('awaiting_renewal_payment_confirmation', 'Awaiting Renewal Payment Confirmation'), ('renewal_payment_confirmed', 'Renewal Payment Confirmed'), ('renewed', 'Renewed'), ('awaiting_document_resubmission', 'Awaiting Document Resubmission'), ('withdrawn', 'Withdrawn')], default='draft', max_length=50),
        ),
    ]
