# Generated by Django 4.2.30 on 2026-07-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_add_legacy_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='locality',
            field=models.CharField(blank=True, help_text='Town/estate/community — a finer check than ward', max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
