# Generated by Django 4.2.30 on 2026-07-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_application_latitude_application_locality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ward',
            field=models.CharField(choices=[('ward_a', 'Ward A (Ibeju 1)'), ('ward_b', 'Ward B (Ibeju 2)'), ('ward_c1', 'Ward C1 (Orimedu 1)'), ('ward_c2', 'Ward C2 (Orimedu 2)'), ('ward_d', 'Ward D (Orimedu 3)'), ('ward_e', 'Ward E (Iwerekun 1)'), ('ward_f', 'Ward F (Iwerekun 2)')], default='ward_a', max_length=20),
        ),
    ]
