# Generated by Django 4.2.30 on 2026-07-29 09:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_alter_application_ward'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=150)),
                ('pin_hash', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'committee_members',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('general_comment_to_applicant', models.TextField(blank=True)),
                ('overall_recommendation', models.TextField(blank=True)),
                ('decision', models.CharField(default='recommend', max_length=20)),
                ('forwarded_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='committee_review', to='applications.application')),
            ],
            options={
                'db_table': 'committee_reviews',
            },
        ),
        migrations.CreateModel(
            name='CommitteeMemberComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('signature', models.CharField(help_text='Typed signature of the member', max_length=150)),
                ('recommendation', models.CharField(choices=[('recommend', 'Recommend for approval'), ('not_recommend', 'Do not recommend'), ('abstain', 'Abstain / neutral')], default='recommend', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_comments', to='applications.application')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='applications.committeemember')),
            ],
            options={
                'db_table': 'committee_member_comments',
                'ordering': ['member__number'],
                'unique_together': {('application', 'member')},
            },
        ),
    ]
