# Generated by Django 4.2.30 on 2026-07-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_committeemember_committeereview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_royalty_exempt',
            field=models.BooleanField(default=False, help_text='Chairman-granted: royalty pays only the application fee (Stage C waived)'),
        ),
        migrations.AddField(
            model_name='application',
            name='pole_number',
            field=models.CharField(blank=True, help_text='Pole number for the street sign', max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='signboard_number',
            field=models.CharField(blank=True, help_text='Physical signboard number', max_length=50),
        ),
    ]
