# Generated by Django 4.2.30 on 2026-07-30 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_application_is_royalty_exempt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeSubmissionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_submission_reviews', to='applications.application')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.committeemember')),
            ],
            options={
                'db_table': 'committee_submission_reviews',
                'unique_together': {('application', 'member')},
            },
        ),
    ]
