# Generated by Django 4.2.30 on 2026-08-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_committeesubmissionreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='signboard_seq',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Auto-issued sequence number for signboard/pole; released and recycled on decline', null=True),
        ),
    ]
