# Generated by Django 4.2.30 on 2026-08-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_application_signboard_seq'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='certificate_released',
            field=models.BooleanField(default=False, help_text='Whether the applicant may download the certificate. Committee/LG chairman can always download.'),
        ),
    ]
