# Generated by Django 4.2.30 on 2026-08-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_application_certificate_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='street_line',
            field=models.TextField(blank=True, default='', help_text='GeoJSON LineString of the chosen road'),
        ),
    ]
