# Generated by Django 4.2.30 on 2026-08-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_application_street_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeemember',
            name='title',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
