# Generated by Django 4.2.30 on 2026-08-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0017_committeemember_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_register_import',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
