# Generated by Django 4.2.30 on 2026-08-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0018_application_is_register_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_renewal_request',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
