# Generated by Django 6.0.4 on 2026-04-16 22:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('stage_a', 'Stage A - Application Processing'), ('stage_c', 'Stage C - Approval & Certificate'), ('renewal', 'Renewal')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Reference Submitted'), ('confirmed', 'Confirmed by Finance'), ('rejected', 'Rejected by Finance')], default='pending', max_length=20)),
                ('amount_expected', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_submitted', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='payment_receipts/')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('finance_remarks', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='applications.application')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
