# Generated by Django 4.2.30 on 2026-07-29 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import payments.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0011_committeemember_committeereview_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial', models.CharField(db_index=True, max_length=40, unique=True)),
                ('payer_name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stage', models.CharField(max_length=30)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('security_code', models.CharField(help_text='HMAC digest for anti-forgery verification', max_length=32)),
                ('pdf', models.FileField(blank=True, null=True, upload_to=payments.models.receipt_upload_path)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='applications.application')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='payments.payment')),
            ],
            options={
                'db_table': 'receipts',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='OfficialSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=payments.models.signature_upload_path)),
                ('signatory_name', models.CharField(default='Council Treasurer', max_length=150)),
                ('signatory_title', models.CharField(default='Council Treasurer, Ibeju-Lekki LGA', max_length=150)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'official_signature',
            },
        ),
    ]
