# Generated by Django 4.2.30 on 2026-08-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_receipt_officialsignature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='stage',
            field=models.CharField(choices=[('stage_a', 'Stage A - Application Processing'), ('stage_c', 'Stage C - Approval & Certificate'), ('revalidation', 'Revalidation'), ('renewal', 'Renewal')], max_length=20),
        ),
    ]
