"""Import already-registered Ibeju-Lekki streets as legacy registrations.

Each street is created as a legacy Application (is_legacy=True) with an issued
certificate, so its name is recorded in the digital registry as already taken.
Data was extracted from the LGA's "Names of Registered Streets" spreadsheet.
"""
import datetime
from django.core.management.base import BaseCommand
from django.db import transaction
from django.utils import timezone

from accounts.models import User, Role
from applications.models import Application, ApplicationStatus, Ward
from config.models import StreetType

# (proposed_street_name, street_type_name, location)
REGISTERED_STREETS = [
    ('Atanda Badmus', 'Street', 'Labora Owode Off Gra'),
    ('Alhaji Sheik Rabiu Adebayo', 'Street', 'Orofun Town'),
    ('B. Niger', 'Street', 'Bankole Town'),
    ('Oba Rafiu Salami', 'Street', 'Ibeju Agbe Town'),
    ('Oba Tajudeen Elemoro', 'Street', 'Oke-Odo/Elemoro'),
    ('Hon. Idowu Eletu', 'Street', 'Awoyaya Town'),
    ('Hon. Tokunboh Amele', 'Street', 'Awoyaya Town'),
    ('Alhaji Bariu Ashafa', 'Street', 'Oke Odo/Elemoro'),
    ('Odunmbaku', 'Street', 'Idinogbo Town'),
    ('Awamaridi', 'Street', 'Idinogbo Town'),
    ('Ogunlana', 'Crescent', 'Awoyaya Town'),
    ('Prince Bayo Balogun', 'Way', 'Elemoro/Okolomi'),
    ('Actor', 'Close', 'Awoyaya Town'),
    ('Alh. Talemu', 'Street', 'Igando-Oloja Town'),
    ('Akin Akinshehinya', 'Street', 'Awoyaya Town'),
    ('Adeyinka Oni', 'Street', 'Abijo Town'),
    ('Samson A. Aiyejumo', 'Street', 'Abijo Town'),
    ('Cletus Abobu', 'Street', 'Abijo Town'),
    ('Prince Abiola Shodehinde', 'Street', 'Awoyaya Town'),
    ('Obi Eze E.', 'Street', 'Bogije Town'),
    ('Emma O. Emeagwai', 'Street', 'Abijo Town'),
    ('Alh. Tolani Bakare', 'Street', 'Abijo Town'),
    ('Ramoju Ogunbanwo', 'Street', 'Abijo Gra'),
    ('Dr. Jamal Badmus', 'Street', 'Labora Owode'),
    ('Ashogun Oseni', 'Street', 'Awoyaya Town'),
    ('Monsuru Ajasa', 'Street', 'Awoyaya Town'),
    ('Oluwatoyin Dada', 'Street', 'Oke Odo/Elemoro Town'),
    ('Adetoun Balogun', 'Street', 'Oke Odo/ Elemoro'),
    ('Mercy Oluwabunmi', 'Street', 'Oke Odo/Elemoro'),
    ('Tony Egbohan', 'Street', 'Abijo Town'),
    ('Aderibigbe Dabiri', 'Street', 'Awoyaya Town'),
    ('Temitope Joseph', 'Street', 'Awoyaya Town'),
    ('Hon. Balogun Rashidat', 'Street', 'Abijo Town'),
    ('Taiye Ariwayo', 'Street', 'Awoyaya Town'),
    ('Engr. Gbenga Ogundele', 'Street', 'Awoyaya Town'),
    ('Ayo-Ola Sobajo', 'Street', 'Awoyaya Town'),
    ('Alh. Abiodun Lemomu', 'Street', 'Bogije Town'),
    ('Olalere O.', 'Street', 'Abijo Town'),
    ('Mr. Alliday Karibiye', 'Street', 'Abule Parapo'),
    ('Elebiola Abayomi', 'Street', 'Oke-Odo/Elemono'),
    ('Oshinowo Adebayo', 'Street', 'Awoyaya Town'),
    ('Agboola Kolawole', 'Street', 'Awoyaya Town'),
    ('Ayodele Sajo', 'Street', 'Awoyaya Town'),
    ('Richard Adeniran', 'Street', 'Awoyaya Town'),
    ('Ogundipe Sunday', 'Street', 'Awoyaya Street'),
    ('Olushola Oke', 'Street', 'Lakowe Town'),
    ('Olayinka Adesanya', 'Street', 'Lakwe'),
    ('Prince Frank Egbodo', 'Street', 'Magbon Alade'),
    ('Rakael Ofili', 'Street', 'Lakowe Phase Ii'),
    ('Osaigboro Stephen', 'Street', 'Labora Owode'),
    ('Prince Bayo Balogun', 'Street', 'Oke-Odo/Elemoro'),
    ('Balikis Ojomo Amoke', 'Street', 'Lakowe Town'),
    ('Oladimeji Ajijola', 'Street', 'Otunla Town'),
    ('Lucy Dupe Adeoti', 'Street', 'Awoyaya Town'),
    ('Abisola Isokpehi', 'Street', 'Awoyaya Town'),
    ('Alhaji Fatai Eletu', 'Street', 'Awoyaya Town'),
    ('Oxyley', 'Drive', 'Abijo Town'),
    ('Adeola Ibrahim Alabede', 'Street', 'Bogije Town'),
    ('Samuel Oyesola', 'Street', 'Bankole Town'),
    ('Taiwo Adebambo', 'Street', 'Ibeju Agbe Town'),
    ('Chief Lewis Obinna', 'Avenue', 'Labora'),
    ('Animashaun Muka', 'Drive', 'Awoyaya Town'),
    ('Otunba Muniru Elemono', 'Street', 'Bogije Town'),
    ('Ehoho Francis', 'Street', 'Oribanwa Town'),
    ('Abijo-Oko Abe Community', 'Street', 'Abijo Town'),
    ('Hassan Nwakago Lukumi', 'Street', 'Awoyaya Town'),
    ('High Chief Cosmas Agwu', 'Street', 'Oribanwa'),
    ('Ujomu Sylvester', 'Street', 'Awoyaya Town'),
    ('Aliu Alagbo Onilewaji', 'Street', 'Oribanwa'),
    ('General A.V. Okpobrisi', 'Avenue', 'Awoyaya Town'),
    ('Chidi Okpala', 'Close', 'Abijo Town'),
    ('Brig. Gen. Life Ajemba', 'Street', 'Abule Panu Town'),
    ('Bafaj', 'Crescent', 'Ogunfayo Town Eputu'),
    ('Akanbi Sabiu Odofin', 'Street', 'Lagasa Town'),
    ('Elizabeth Alabede', 'Street', 'Bogije Town'),
    ('Ibrahim Muibi Alabede Bogije Town', 'Street', ''),
    ('Mutiu Olasunkanmi Saheed', 'Street', 'Oribanwa Town'),
    ('Solomon Hassan', 'Way', 'Akodo Town'),
    ('Engr. Abiola Olowu', 'Street', 'Oke-Odo/Elemoro'),
    ('Prince Adebayo Fusigboye', 'Street', 'Lakowe Ph Ii'),
    ('Ogunshakin Temidayo', 'Street', 'Awoyaya Street'),
    ('Dorothy Agunpopo', 'Street', 'Adeba Town'),
    ('Babatunde Anifowose', 'Street', 'Abijo G.R.A'),
    ('Modupe Kolawole', 'Street', 'Abule Parapo Town'),
    ('Anderson Okoro', 'Avenue', 'Imedu-Awoyaya'),
    ('Nathaniel Olade', 'Close', 'Bogije Town'),
    ('Mutiat Sadiku Adegbite', 'Close', 'Abijo Town'),
    ('Alh. Abiola Tijani', 'Street', 'Elepete Town'),
    ('Yesiru Idogun Tomola', 'Street', 'Imalete Alafia'),
    ('Prince Bisiriyu Idogun Owo Okadec', 'Street', 'Imalete Alafia'),
    ('Prince Abimiyau Idogun', 'Street', 'Imalete Alafia'),
    ('Prince Surakat Idogun', 'Street', 'Imalete Alafia'),
    ('Prince Salaudeen Idogun', 'Street', 'Imalete Alafia'),
    ('Churchill Olaiya', 'Street', 'Kaiyetoro Town'),
    ('Prince Ogeruwa', 'Street', 'Imalete Alafia Town'),
    ('Olowo Eti Ebute', 'Street', 'Awoyaya Town'),
    ('Ifatedo Elemono', 'Street', 'Oke-Odo Elero Town'),
    ('Segun Adebanjo', 'Street', 'Awoyaya Town'),
    ('Amity', 'Crescent', 'Abijo Town'),
    ('Amity', 'Street', 'Abijo Town'),
    ('Molusi', 'Close', 'Onishon/Lakowe Town'),
    ('Nnagmeka Odunze', 'Street', 'Gbetu Town'),
    ('Olu Joseph', 'Street', 'Lakowe Town'),
    ('Abass Bab-Salami', 'Street', 'Oke-Odo Town'),
    ('Ogunyomi', 'Crescent', 'Lakowe Town'),
    ('Taye Salawu', 'Street', 'Adeba Town'),
    ('Olufemi Adegbo Blessing', 'Street', 'Oke-Odo'),
    ('Sulaimon Arebi', 'Street', 'Araromi Ibeju Town'),
    ('Alhaja Omolola Azeez Ehintokun', 'Street', 'Awoyaya'),
    ('Ayobami Oyewale', 'Close', 'Orimedu Town'),
    ('Bayode Badmus', 'Street', 'Gbetu Town'),
    ('Owopeju Abayomi', 'Close', 'Awoyaya Town'),
    ('Moses Udu', 'Street', 'Lakowe Phase Ii'),
    ('Bukola William', 'Close', 'Awoyaya Town'),
    ('Chukwukelu', 'Street', 'Ebute Bogije Town'),
    ('Pst. Collins Chinedu Rockson', 'Close', 'Aiyegbami'),
    ('Dimkda', 'Close', 'Awoyaya Town'),
    ('Efosa Oyemwense Iwerelokun', 'Street', ''),
    ('Dafe Oromony', 'Street', 'Pankere Awoyaya'),
    ('Mabokunrinje', 'Street', 'Aiyeteju Town'),
    ('Amudalatuhi', 'Street', 'Lakowe Town'),
    ('Dinald Odusanmi', 'Close', 'Awoyaya'),
    ('Chief Oma Eyewuoma', 'Road', 'Abijo Gra'),
    ('Babatunde Raji Fashola', 'Street', 'Idinogbo Town'),
    ('Asiwaju Bola Ahmed Tinubu', 'Street', 'Idinogbo Town'),
    ('Bimpe Carrena', 'Crescent', 'Abijo Gra'),
    ('Adekoya Eyiowulawi', 'Street', 'Bankole Town'),
    ('Kamil Ibilola', 'Street', 'Igando- Oloja'),
    ('Lead Forte Gate', 'Close', 'Awoyaya Town'),
    ('Noshusi', 'Road', 'Odofin Town'),
    ('Chief Ezeugo Emesuanwu', 'Street', 'Kaiyetoro'),
    ('Bablon Bafaj', 'Avenue', 'Oribanwa Town'),
    ('Adebayo Adebowale', 'Street', 'Onosa Town'),
    ('James Alabijo', 'Street', 'Abijo Town'),
    ('Isaac Etim', 'Close', 'Destiny Home Abijo Town'),
    ('Alimi Olufunke Adeola', 'Street', 'Owode Labona'),
    ('Bafaj', 'Way', 'Abule Panu'),
    ('Alh. Gbengba Sheriff Adeleke', 'Street', 'Abijo'),
    ('Corona', 'Drive', 'Abijo Gra'),
    ('Obano Darlington', 'Street', 'Ofiran Town'),
    ('Weloye Olarinoye', 'Close', 'Awoyaya Town'),
    ('Lekan Carrena', 'Avenue', 'Abijo Town'),
    ('Sir Babatunde Anjous', 'Street', 'Ojue Town'),
    ('Mrs Basirat Abiola Balogun', 'Street', 'Abule Panu'),
    ('Engr. Babatunde Bakare', 'Crescent', 'Abijo Gra'),
    ('Orisatuwa Eletu', 'Street', 'Awoyaya Town'),
    ('Eletu Obido', 'Road', 'Awoyaya Town'),
    ('Alla Arilesere', 'Close', 'Eputu Town'),
    ('Ajose', 'Street', 'Lagasa Phase Ii'),
    ('Olakunle Rasak Oki', 'Street', 'Awoyaya Town'),
    ('Kamoru Bankole', 'Street', 'Bogije Town'),
    ('S.O.A. Ade Owolebi', 'Close', 'Lakowe Town'),
    ('Prince Ade Owolebi', 'Close', 'Lakowe Town'),
    ('Chief Kunle Ogunade', 'Street', 'Igando Oloja'),
    ('Emmine Ebong', 'Road', 'Bogije Town'),
    ('Josephine Oluwatoyin Osobo', 'Street', 'Adeba'),
    ('Chief (Mrs) Yomi Balogun', 'Crescent', 'Imalete Alafia'),
    ('Ebi Odeygah', 'Street', 'Awoyaya Town'),
    ('Rev. Nicholas Iyere Isibon', 'Street', 'Bankole'),
    ('Nwaham', 'Close', 'Araromi Ibeju Town'),
    ('Alhaji Olowolayemo', 'Crescent', 'Awoyaya Town'),
    ('Nimota Shittabey', 'Street', 'Awoyaya Town'),
    ('Giwa Oritoke', 'Crescent', 'Gbetu Village'),
    ('Newville Atigan', 'Street', 'Ogunfayo'),
    ('Abiola Shekoni', 'Street', 'Lakowe Phase Ii'),
    ('Babalola Fajobi', 'Close', 'Aiyegbami'),
    ('Chukwueloke Emmanuel', 'Road', 'Ogunfayo'),
    ('Osaretin Ighile', 'Street', 'Oko Ile Town'),
    ('Alhaji Raheem O. Alli', 'Street', 'Bogije Town'),
    ('Alhaji Disu Muyideen', 'Road', 'Bogije Town'),
    ('Shalom Dark', 'Street', 'Casia-Abijo Town'),
    ('Adebayo Oshikanlu', 'Crescent', 'Casia- Abijo'),
    ('Pastor Lanipekun Lawal', 'Road', 'Gbetu Town'),
    ('Alhaji Babatunde Eletu', 'Street', 'Awoyaya Town'),
    ('Ogunderu Eletu', 'Street', 'Awoyaya Town'),
    ('Berry Okuwobi', 'Street', 'Okolomi Town'),
    ('Alh. Wasiu Abanjo', 'Street', 'Eputu Town'),
    ('Gen. K. Agboola-Vigo', 'Close', 'Gulf Lake'),
    ('Baeon', 'Close', 'Oko -Ile Town'),
    ('Bivada Tank Farm', 'Road', 'Oko-Ile Town'),
    ('S.D.A Church', 'Road', 'Otunla Town'),
    ('Rotimi Ogunleye', 'Street', 'Abijo Town'),
    ('S.B.J. Olaonipekun', 'Street', 'Abijo Town'),
    ('Sin. Noel Onyekwelu', 'Street', 'Abule Panapo Town'),
    ('Liadi Eletu', 'Street', 'Awoyaya Town'),
    ('Alowo-Eshin Eletu', 'Street', 'Awoyaya Town'),
    ('Olabode Eletu Odibo', 'Street', 'Awoyaya Town'),
    ('Olowo Eti Ebute', 'Lane', 'Awoyaya Town'),
    ('Anuolwapo Adenkoya', 'Street', 'Ibeju Town'),
    ('Oluwashemilore Lawani', 'Street', 'Awoyaya Town'),
    ('Chief D.O. Akpoton', 'Street', 'Bogije Town'),
    ('Francis Ayo Emiolan', 'Street', 'Oribanwa Town'),
    ('Bamiyefa Asekun', 'Road', 'Kaiyetoro Town'),
    ('Obilaj', 'Way', 'Elerangbe'),
    ('Akintunde', 'Close', 'Aiyeteju Town'),
    ('Paul O. Oyekwene', 'Close', 'Awoyaya Town'),
    ('Nurudeen Shobajo', 'Street', 'Abijo Gra'),
    ('Adeboye Omotoso', 'Close', 'Iraboko Awoyaya'),
    ('Augustine Ohwovoriole', 'Close', 'Awoyaya Town'),
    ('Anthony Onoabhagbe', 'Close', 'Lakowe Town'),
    ('Saliu Oluwa', 'Street', 'Awoyaya Town'),
    ('Flourish Hall', 'Crescent', 'Bogije Town'),
    ('Aderemi Ajetunmobi', 'Street', 'Orimedu Town'),
    ('Prince Adedeji Fasasi', 'Close', 'Lakowe Phase Ii'),
    ('General Ibim Lawson Awoyaya Town', 'Street', ''),
    ('Adebowale Bakare Orimedu Town', 'Street', ''),
    ('Sanni Adeneye Igando Oloja', 'Street', ''),
    ('Kanmi Oyegunle Abijo Town', 'Street', ''),
    ('Olu Oke', 'Street', 'Kayetoro Town'),
    ('Chief Aruna Baale', 'Road', 'Igando Oloja Town'),
    ('Moses Adetunmobi', 'Way', 'Idi-Oyin Araromi Town'),
    ('Omoniyi Agbaje', 'Close', 'Destiny Estate Abijo'),
    ('Babatunde Lamidi Sanni Vilac', 'Way', 'Abijo'),
    ('Comfort Ugheoke', 'Street', 'Oko-Ile Lakowe Town'),
    ('Odebode Olabisi', 'Street', 'Iraboko Awoyaya Town'),
    ('Bld. O.A. Bolarin', 'Street', 'Abule Parapo'),
    ('Oseghale Osemudiame', 'Street', 'Igando- Oloja'),
    ('Emeka Ajero', 'Close', 'Fidiso Estate Abijo'),
    ('Noibi Sodiq Haruna', 'Street', 'Igando- Oloja'),
    ('Alh. Liadi Lukman Olajide', 'Street', 'Elepete Town'),
    ('Florence Modupe Oguntuasi', 'Street', 'Abijo Gra'),
    ('Chief B.A Lamina', 'Street', 'Iberekodo Town'),
    ('Chief T.A.R. Salami', 'Street', 'Iberekodo Town'),
    ('S.B. Aro', 'Street', 'Iberekodo Town'),
    ('K.D. Oyadongha Abijo Gra', 'Street', ''),
    ('Ken Narebon', 'Close', 'Ibeju Araromi'),
    ('Yesin Alagabi', 'Street', 'Orimedu Town Phase Ii'),
    ('Hon. Yusuf Adetona Balina Jegede Orimedu Town', 'Street', ''),
    ('Akubuo Pauline Akubuo', 'Street', 'Oribanwa'),
    ('Lawal Tajudeen Ogeye Badore Town', 'Street', ''),
    ('Shitta Yakuba Magbon Alade', 'Street', ''),
    ('Mike Igbokwe', 'Street', 'Abijo Gra'),
    ('Tajudeen Olawale', 'Close', 'Desa Town'),
    ('Babatunde Balogun Savana Spring', 'Drive', 'Abijo'),
    ('John Owokade', 'Close', 'Wakas'),
    ('Rev. Janet Tomomewo Taro Laponaga Town', 'Street', ''),
    ('Olajide Sawyer Bogije Town', 'Street', ''),
    ('Matthew Onyilo', 'Close', 'Aiyeteju Town'),
    ('Ola Olu Heritage', 'Street', 'Onishon'),
    ('Paul Adedamola', 'Street', 'Elemoro Street'),
    ('Hon. Samsondeen Adebanjo', 'Close', 'Eputu Town'),
    ('Segun Onabanjo', 'Crescent', 'Bogije Town'),
    ('Akerele Bakare', 'Lane', 'Kaiyetoro Town'),
    ('Ali Balogun', 'Street', 'Kaiyetoro Town'),
    ('Rittner', 'Close', 'Laporaga Town'),
    ('Owokade Adeolu', 'Street', 'Igando Oloja'),
    ('Ogbobe Augustine', 'Street', 'Abijo Town'),
    ('Alhaja Sidikat Amope', 'Street', 'Imalete Alafia'),
    ('Ademola Afonja', 'Street', 'Eleranigbe'),
    ('Godwin Dike', 'Close', 'Oko-Olomi'),
    ('Festus S. Kajola', 'Street', ''),
    ('Success', 'Way', 'Close Igando- Oloja'),
    ('Chief Jerry Ndu', 'Street', 'Igando-Oloja'),
    ('Olusoji Toyin Oyeewole', 'Close', 'Aiyeteju'),
    ('Jumat Lawal', 'Street', 'Parapo Iwenekun'),
    ('Lamina', 'Street', 'Iberekodo'),
    ('Lawal Oladehinde', 'Street', 'Museyipo'),
    ('Ocean', 'Drive', 'Orimedu'),
    ('Rafiu Salami', 'Street', 'Orimedu Town'),
    ('S.A. Olayemi', 'Street', 'Akodo'),
    ('Saheed Adeshoye', 'Street', 'Magbon Alade'),
    ('Idisewe', 'Street', 'Akodo'),
    ('Oketim', 'Street', 'Ibeju Agber'),
    ('Orunmija', 'Road', 'Solu Alade'),
    ('Tabo', 'Street', 'Street Akodo'),
    ('Salami', 'Street', 'Orimedu'),
    ('Abass Ogunlaja', 'Street', 'Orofun Town'),
    ('Adeboye', 'Street', 'Eputu Town'),
    ('Alh. Muritala Eletu', 'Lane', 'Awoyaya Town'),
    ('Ajiwe', 'Close', 'Oju-Ile'),
    ('Alh. Ganiyu Eletu', 'Street', 'Awoyaya Town'),
    ('Alh. Sikiru Adeboyejo', 'Close', 'Awoyaya Town'),
    ('Afoke', 'Close', 'Oribanwa Town'),
    ('Alh. Olowolayemo', 'Crescent', 'Awoyaya Town'),
    ('Adekoya', 'Street', 'Onosa'),
    ('Ade Olowopopo', 'Avenue', 'Gbetu Town'),
    ('Alh. Arilesere', 'Close', 'Abijo Town'),
    ('Awoyaya', 'Road', 'Awoyaya Town'),
    ('Bayo Williams Awoyaya Town', 'Street', ''),
    ('Camini', 'Close', 'Awoyaya Town'),
    ('Charlotte', 'Close', 'Awoyaya Town'),
    ('Baale', 'Avenue', 'Awoyaya Town'),
    ('Bayo William', 'Street', 'Awoyaya Town'),
    ('Baale Kanibawi', 'Street', 'Awoyaya Town'),
    ('Eletu', 'Street', 'Awoyaya Town'),
    ('Gafaru Eletu', 'Street', 'Awoyaya Town'),
    ('God Own', 'Street', 'Golf Lakowe'),
    ('Kokoro', 'Street', 'Awoyaya Town'),
    ('Marble', 'Street', 'Awoyaya Town'),
    ('Olamide Igiaba', 'Street', 'Oribanwa'),
    ('Okesuna', 'Street', 'Lakowe Phase Ii'),
    ('Ologbon', 'Road', 'Magbon Alade'),
    ('Ukpakanagbanudumri Comfort Home Abijo', 'Street', ''),
    ('Rich Njoku', 'Street', 'Awoyaya Town'),
    ('New Jerusalem', 'Street', 'Bogije'),
    ('Olorunlambe', 'Road', 'Awoyaya Town'),
    ('Nancy Niwola', 'Street', 'Awoyaya Town'),
    ('Musiliu Eletu', 'Street', 'Awoyaya Town'),
    ('M.K.O', 'Street', 'Aiyeteju'),
    ('Pastor Dada', 'Crescent', 'Lakowe Phase Ii'),
    ('Samuel Uduerbo', 'Street', 'Lakowe Phase Ii'),
    ('Saliu Redeemed', 'Street', 'Bogije'),
    ('Oyindamola Arogunmati', 'Crescent', 'Awoyaya Town'),
    ('Omo B & Son', 'Street', 'Ibeju Agbe'),
    ('Regal Iwaya', 'Street', 'Awoyaya'),
    ('Prof Tunji Bello', 'Street', 'Abijo'),
    ('Ken Narebor', 'Street', 'Eputu'),
    ('Parapo Community', 'Road', 'Awoyaya'),
    ('Peter Okewu', 'Close', 'Abijo'),
    ('Paul Osigala', 'Street', 'Abijo'),
    ('Rafiu Adebanjo', 'Street', 'Imedu'),
    ('Yisa Dogo', 'Street', 'Iraboko'),
    ('Sanni Yesru Eletu', 'Street', 'Awoyaya Town'),
    ('Unity', 'Street', 'Gbetu'),
    ('Star Teeth', 'Street', 'Gbetu'),
    ('Tayo Musari', 'Street', 'Lakowe Phase Ii'),
    ('Watch Tower', 'Street', 'Fidiso Abijo'),
    ('Taye Salau', 'Street', 'Labora'),
    ('W.G. Core', 'Crescent', 'Abijo'),
    ('Ayodeji Oyebobola', 'Street', 'Abijo'),
    ('Olayemi Fagbuyi', 'Street', 'Abijo'),
    ('Abolarin Clement', 'Street', 'Bogije'),
    ('Christopher Sunday', 'Street', 'Eleko'),
    ('Alhaji O. Idowu', 'Street', 'Awoyaya'),
    ('Surajudeen Bello', 'Street', 'Awoyaya'),
    ('Sunmisola Aboyadi Cole', 'Street', 'Labora'),
    ('Amid Jasper', 'Street', 'Lakowe'),
    ('Temitope K. Adesina', 'Street', 'Baba Adisa'),
    ('Mosunmola Faloye', 'Street', 'Abijo'),
    ('Felix Omoniyi', 'Street', 'Onosa'),
    ('Constance Omoniyi', 'Close', 'Onosa'),
    ('Isaac Eyinife', 'Street', 'Lakowe'),
    ('John Sokoya', 'Close', 'Abijo'),
    ('Aderemi Peter', 'Street', 'Awoyaya'),
    ('Idayat Tolani Bello', 'Street', 'Awoyaya'),
    ('Okunola Waheed', 'Street', 'Awoyaya'),
    ('Ashafa Elemo', 'Street', 'Elesekan'),
    ('Babajide Sanwo-Olu', 'Avenue', 'Igando'),
    ('Medallion', 'Crescent', 'Mopo Ijebu'),
    ('Adeles Market', 'Street', 'Bojide'),
    ('Abdulfattah Giwa', 'Close', 'Losoro'),
    ('Sheba Resort', 'Avenue', 'Mopo Ijebu'),
    ('Wazsholly', 'Avenue', 'Elesekan'),
    ('Alogba', 'Avenue', 'Olupa Town'),
    ('Modupe', 'Close', 'Awoyaya'),
    ('Bosede Dawodu', 'Close', 'Igando'),
    ('Funmi Ademiluwa', 'Road', 'Eleko'),
    ('Bankole Williams', 'Crescent', 'Solu Ade'),
    ('Hosein Oniwonlu', 'Close', 'Onishon'),
    ('F.B. Amieneke', 'Street', 'Malete'),
    ('Aniyikaye Raji', 'Street', 'Malete'),
    ('Mercury M/Ige-Alade Indr.', 'Road', 'Olupa'),
]

LEGACY_APPLICANT_EMAIL = 'legacy-registry@ibeju-lekki.gov.ng'


class Command(BaseCommand):
    help = 'Import already-registered streets as legacy (pre-digital) registrations.'

    @transaction.atomic
    def handle(self, *args, **options):
        # A single system account owns all imported legacy records.
        owner, created = User.objects.get_or_create(
            email=LEGACY_APPLICANT_EMAIL,
            defaults={
                'first_name': 'Legacy',
                'last_name': 'Registry',
                'role': Role.APPLICANT,
                'is_active': False,
            },
        )
        if created:
            owner.set_unusable_password()
            owner.save()
            self.stdout.write('Created system owner account for legacy records.')

        street_types = {st.name: st for st in StreetType.objects.all()}
        default_type = street_types.get('Street')
        today = datetime.date.today()
        expiry = today.replace(year=today.year + 5)

        created_count = 0
        skipped = 0
        missing_type = 0
        for name, type_name, location in REGISTERED_STREETS:
            st = street_types.get(type_name) or default_type
            if st is None:
                missing_type += 1
                continue
            # Skip if an identical name+type already exists (idempotent re-runs).
            exists = Application.objects.filter(
                proposed_street_name__iexact=name, street_type=st
            ).exists()
            if exists:
                skipped += 1
                continue
            Application.objects.create(
                applicant=owner,
                proposed_street_name=name,
                street_type=st,
                location_description=location or 'Ibeju-Lekki LGA',
                ward=Ward.WARD_A,
                lga_area='Ibeju-Lekki',
                status=ApplicationStatus.CERTIFICATE_ISSUED,
                is_legacy=True,
                certificate_issued_at=timezone.now(),
                expires_at=expiry,
                google_map_uploaded=True,
                signpost_installed=True,
            )
            created_count += 1

        self.stdout.write(self.style.SUCCESS(
            f'Registered streets imported — created: {created_count}, '
            f'skipped (already present): {skipped}, missing street type: {missing_type}'
        ))
        self.stdout.write(self.style.SUCCESS('Done.'))
