# Generated by Django 6.0.4 on 2026-04-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('nin_verification_slip', 'NIN Verification Slip'), ('passport_photograph', 'Passport Photograph'), ('royal_fathers_recognition_letter', 'Royal Fathers Recognition Letter'), ('survey_property_document', 'Survey Property Document')], max_length=50),
        ),
    ]
