# Generated by Django 4.2.30 on 2026-07-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_is_rejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('nin_verification_slip', 'NIN Verification Slip'), ('passport_photograph', 'Passport Photograph'), ('royal_fathers_recognition_letter', 'Royal Fathers Recognition Letter'), ('survey_property_document', 'Survey Property Document'), ('cda_recommendation_letter', 'CDA / Landlord Association Recommendation Letter')], max_length=50),
        ),
    ]
