# Generated by Django 4.2.30 on 2026-07-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='direction',
            field=models.CharField(choices=[('submission', 'Applicant submission'), ('issued', 'Issued to applicant by Council')], default='submission', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, help_text='Label for Council-issued documents', max_length=200),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('nin_verification_slip', 'NIN Verification Slip'), ('passport_photograph', 'Passport Photograph'), ('royal_fathers_recognition_letter', 'Royal Fathers Recognition Letter'), ('survey_property_document', 'Survey Property Document'), ('cda_recommendation_letter', 'CDA / Landlord Association Recommendation Letter'), ('admin_correspondence', 'Correspondence / Letter from the Council')], max_length=50),
        ),
    ]
